// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPqx8IS86Q-wQrh4AAqmyIsa6Lq8Cco3o',
    appId: '1:227827544826:web:edd82b8403395342a48f43',
    messagingSenderId: '227827544826',
    projectId: 'highprogrammingftest',
    authDomain: 'highprogrammingftest.firebaseapp.com',
    databaseURL: 'https://highprogrammingftest-default-rtdb.firebaseio.com',
    storageBucket: 'highprogrammingftest.appspot.com',
    measurementId: 'G-S97GKZVZJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCysx9nHv7toNiUTHMOSqAEwH2NKPMpucw',
    appId: '1:227827544826:android:74cbb2b8a8a6f988a48f43',
    messagingSenderId: '227827544826',
    projectId: 'highprogrammingftest',
    databaseURL: 'https://highprogrammingftest-default-rtdb.firebaseio.com',
    storageBucket: 'highprogrammingftest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmY4_t4ImjnwP9cmqaFdmfQOeWPqlEd-Q',
    appId: '1:227827544826:ios:463b165381b54a03a48f43',
    messagingSenderId: '227827544826',
    projectId: 'highprogrammingftest',
    databaseURL: 'https://highprogrammingftest-default-rtdb.firebaseio.com',
    storageBucket: 'highprogrammingftest.appspot.com',
    iosClientId: '227827544826-p1on66esli0qvpjsegv7n69iv8690686.apps.googleusercontent.com',
    iosBundleId: 'com.example.highFinalteste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmY4_t4ImjnwP9cmqaFdmfQOeWPqlEd-Q',
    appId: '1:227827544826:ios:592fb71ea129171da48f43',
    messagingSenderId: '227827544826',
    projectId: 'highprogrammingftest',
    databaseURL: 'https://highprogrammingftest-default-rtdb.firebaseio.com',
    storageBucket: 'highprogrammingftest.appspot.com',
    iosClientId: '227827544826-4dp1i7siotel3v6vbptr9kifp60hnv4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.highFinalteste.RunnerTests',
  );
}
